export default { entries: [
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Town Hall',
    time_seconds: '45480',
    time_str: '12:38 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:36 PM',
    estimated_arrival_time_seconds: 45360,
    estimated_departure_time_str: '12:38 PM',
    estimated_departure_time_seconds: 45480,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Town Hall',
    time_seconds: '45480',
    time_str: '12:38 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:36 PM',
    estimated_arrival_time_seconds: 45360,
    estimated_departure_time_str: '12:38 PM',
    estimated_departure_time_seconds: 45480,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Anzac',
    time_seconds: '45660',
    time_str: '12:41 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:40 PM',
    estimated_arrival_time_seconds: 45600,
    estimated_departure_time_str: '12:41 PM',
    estimated_departure_time_seconds: 45660,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Anzac',
    time_seconds: '45660',
    time_str: '12:41 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:40 PM',
    estimated_arrival_time_seconds: 45600,
    estimated_departure_time_str: '12:41 PM',
    estimated_departure_time_seconds: 45660,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'West Footscray',
    time_seconds: '44460',
    time_str: '12:21 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:06 PM',
    estimated_arrival_time_seconds: 43560,
    estimated_departure_time_str: '12:21 PM',
    estimated_departure_time_seconds: 44460,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Middle Footscray',
    time_seconds: '44520',
    time_str: '12:22 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '1',
    estimated_arrival_time_str: '12:22 PM',
    estimated_arrival_time_seconds: 44520,
    estimated_departure_time_str: '12:22 PM',
    estimated_departure_time_seconds: 44520,
    estimated_platform: '1'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Footscray',
    time_seconds: '44700',
    time_str: '12:25 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '1',
    estimated_arrival_time_str: '12:23 PM',
    estimated_arrival_time_seconds: 44580,
    estimated_departure_time_str: '12:25 PM',
    estimated_departure_time_seconds: 44700,
    estimated_platform: '1'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Arden',
    time_seconds: '45000',
    time_str: '12:30 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:28 PM',
    estimated_arrival_time_seconds: 44880,
    estimated_departure_time_str: '12:30 PM',
    estimated_departure_time_seconds: 45000,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Parkville',
    time_seconds: '45180',
    time_str: '12:33 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:31 PM',
    estimated_arrival_time_seconds: 45060,
    estimated_departure_time_str: '12:33 PM',
    estimated_departure_time_seconds: 45180,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'State Library',
    time_seconds: '45300',
    time_str: '12:35 PM',
    is_arrival: '0',
    trip_id: 'Z614',
    platform: '2',
    estimated_arrival_time_str: '12:34 PM',
    estimated_arrival_time_seconds: 45240,
    estimated_departure_time_str: '12:35 PM',
    estimated_departure_time_seconds: 45300,
    estimated_platform: '2'
  },
    {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Town Hall',
    time_seconds: '45480',
    time_str: '12:38 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:36 PM',
    estimated_arrival_time_seconds: 45360,
    estimated_departure_time_str: '12:38 PM',
    estimated_departure_time_seconds: 45480,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Anzac',
    time_seconds: '45660',
    time_str: '12:41 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:40 PM',
    estimated_arrival_time_seconds: 45600,
    estimated_departure_time_str: '12:41 PM',
    estimated_departure_time_seconds: 45660,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Malvern',
    time_seconds: '46140',
    time_str: '12:49 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '4',
    estimated_arrival_time_str: '12:48 PM',
    estimated_arrival_time_seconds: 46080,
    estimated_departure_time_str: '12:49 PM',
    estimated_departure_time_seconds: 46140,
    estimated_platform: '4'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Caulfield',
    time_seconds: '46320',
    time_str: '12:52 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '4',
    estimated_arrival_time_str: '12:51 PM',
    estimated_arrival_time_seconds: 46260,
    estimated_departure_time_str: '12:52 PM',
    estimated_departure_time_seconds: 46320,
    estimated_platform: '4'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Carnegie',
    time_seconds: '46440',
    time_str: '12:54 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:53 PM',
    estimated_arrival_time_seconds: 46380,
    estimated_departure_time_str: '12:54 PM',
    estimated_departure_time_seconds: 46440,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Murrumbeena',
    time_seconds: '46560',
    time_str: '12:56 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:55 PM',
    estimated_arrival_time_seconds: 46500,
    estimated_departure_time_str: '12:56 PM',
    estimated_departure_time_seconds: 46560,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Hughesdale',
    time_seconds: '46620',
    time_str: '12:57 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:57 PM',
    estimated_arrival_time_seconds: 46620,
    estimated_departure_time_str: '12:58 PM',
    estimated_departure_time_seconds: 46680,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Oakleigh',
    time_seconds: '46800',
    time_str: '1:00 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:59 PM',
    estimated_arrival_time_seconds: 46740,
    estimated_departure_time_str: '1:00 PM',
    estimated_departure_time_seconds: 46800,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Huntingdale',
    time_seconds: '46920',
    time_str: '1:02 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '1:02 PM',
    estimated_arrival_time_seconds: 46920,
    estimated_departure_time_str: '1:02 PM',
    estimated_departure_time_seconds: 46920,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Clayton',
    time_seconds: '47100',
    time_str: '1:05 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '1:05 PM',
    estimated_arrival_time_seconds: 47100,
    estimated_departure_time_str: '1:05 PM',
    estimated_departure_time_seconds: 47100,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Arden',
    time_seconds: '45000',
    time_str: '12:30 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:28 PM',
    estimated_arrival_time_seconds: 44880,
    estimated_departure_time_str: '12:30 PM',
    estimated_departure_time_seconds: 45000,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Arden',
    time_seconds: '45000',
    time_str: '12:30 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:28 PM',
    estimated_arrival_time_seconds: 44880,
    estimated_departure_time_str: '12:30 PM',
    estimated_departure_time_seconds: 45000,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'Parkville',
    time_seconds: '45180',
    time_str: '12:33 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:31 PM',
    estimated_arrival_time_seconds: 45060,
    estimated_departure_time_str: '12:33 PM',
    estimated_departure_time_seconds: 45180,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'Parkville',
    time_seconds: '45180',
    time_str: '12:33 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:31 PM',
    estimated_arrival_time_seconds: 45060,
    estimated_departure_time_str: '12:33 PM',
    estimated_departure_time_seconds: 45180,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '1',
    station: 'State Library',
    time_seconds: '45300',
    time_str: '12:35 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:34 PM',
    estimated_arrival_time_seconds: 45240,
    estimated_departure_time_str: '12:35 PM',
    estimated_departure_time_seconds: 45300,
    estimated_platform: '2'
  },
  {
    timetable_num: '0',
    day_type: '3',
    to_city: '0',
    station: 'State Library',
    time_seconds: '45300',
    time_str: '12:35 PM',
    is_arrival: '0',
    trip_id: 'C985',
    platform: '2',
    estimated_arrival_time_str: '12:34 PM',
    estimated_arrival_time_seconds: 45240,
    estimated_departure_time_str: '12:35 PM',
    estimated_departure_time_seconds: 45300,
    estimated_platform: '2'
  }
], created: 1764552248000 }